name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up C++ environment
      run: sudo apt-get install -y g++ make
    - name: Build
      run: |
        g++ -std=c++17 -o quine_mccluskey main.cpp
    - name: Test
      run: |
        ./quine.cpp
